name: Send Notification

on:
  workflow_dispatch:
  schedule:
    - cron: '30 0 * * *'

jobs:
  fast-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Requests
        run: pip install requests

      - name: Execute Notification
        run: python bot.py
